version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: yarn start
    env_file:
      - .env
    ports:
      - 3333:3333

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_movie_api
    ports:
     - 5432:5432

volumes:
  postgres-data:
